#!/bin/bash
# Use informations in 02_info/simulation_parameters.csv to run multiple
# simulations with 01_scripts/01_coelopa_inversion_selection.py

# Global variables
PARAMETER_FILE=$1
NUMBER_REPLICATES=$2
OUTPUT_FOLDER=03_simulations

# Create empty simulation folders
grep -v "#" "$PARAMETER_FILE" |
    cut -d "," -f 1 |
    sort -u |
    while read experiment
    do
        rm -r "$OUTPUT_FOLDER"/"$experiment" 2>/dev/null
        mkdir "$OUTPUT_FOLDER"/"$experiment" 2>/dev/null
    done

# Launch jobs
grep -v "#" "$PARAMETER_FILE" |
    while read line
    do
        # Read parameters into array
        IFS=',' read -r -a array <<< "$line"

        # For each parameter set, run $NUMBER_REPLICATES simulations
        seq -w "$NUMBER_REPLICATES" |
            parallel -k -j 10 ./target/release/coelopa_fastsim \
                -o "$OUTPUT_FOLDER"/"${array[0]}"/"${array[1]}"_replicate_{}.csv \
                    --experiment-name             "${array[1]}"   \
                    --number-generations          "${array[3]}"   \
                    --number-eggs-per-generation  "${array[4]}"   \
                    --number-eggs-per-female      "${array[5]}"   \
                    --proportion-females          "${array[6]}"   \
                    --proportion-aa               "${array[7]}"   \
                    --proportion-bb               "${array[8]}"   \
                    --survival-global             "${array[9]}"   \
                    --survival-females-aa         "${array[10]}"  \
                    --survival-females-ab         "${array[11]}"  \
                    --survival-females-bb         "${array[12]}"  \
                    --survival-males-aa           "${array[13]}"  \
                    --survival-males-ab           "${array[14]}"  \
                    --survival-males-bb           "${array[15]}"  \
                    --male-success-aa             "${array[16]}"  \
                    --male-success-ab             "${array[17]}"  \
                    --male-success-bb             "${array[18]}"  \
                    --male-freq-dep-coef          "${array[19]}"  \
                    --female-eggs-aa              "${array[20]}"  \
                    --female-eggs-ab              "${array[21]}"  \
                    --female-eggs-bb              "${array[22]}"  \
                    --female-maturation-days      "${array[23]}"  \
                    --male-maturation-days-aa     "${array[24]}"  \
                    --male-maturation-days-ab     "${array[25]}"  \
                    --male-maturation-days-bb     "${array[26]}"  \
                    --maturation-cv               "${array[27]}"  \
                    --environment-time            "${array[28]}"  \
                    --environment-time-variation  "${array[29]}"  #\
                    #--stop-when-fixated -q
    done
